Fix list.sort() argument passing
cmp doesn't exist anymore, and so fails with
```
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/datatypes/mothur.py", line 78, in set_meta
    dataset.metadata.labels.sort()
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy_mutable/mutable_list.py", line 152, in sort
    return super().sort(cmp=cmp, key=key, reverse=reverse)
TypeError: sort() takes at most 2 keyword arguments (3 given)
```